# Generated by Django 2.1.7 on 2019-03-08 13:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('problem', '0001_initial'),
        ('oj', '0005_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(default=uuid.uuid1, max_length=36, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('code', models.TextField(verbose_name='代码')),
                ('status', models.CharField(default='Queueing', max_length=128, verbose_name='状态')),
                ('submit_datetime', models.DateTimeField(auto_now=True, verbose_name='提交时间')),
                ('judge_datetime', models.DateTimeField(verbose_name='判题时间')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oj.Language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='problem.Problem',
                                              verbose_name='题目')),
            ],
        ),
    ]
