# Generated by Django 2.1.7 on 2019-03-08 21:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='lang',
        ),
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(help_text='代码', verbose_name='代码'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(default=uuid.uuid1, help_text='ID', max_length=36, primary_key=True, serialize=False,
                                   verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='judge_datetime',
            field=models.DateTimeField(help_text='判题时间', verbose_name='判题时间'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(help_text='题目', on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='problem.Problem', verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(default='Queueing', help_text='状态', max_length=128, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submit_datetime',
            field=models.DateTimeField(auto_now=True, help_text='提交时间', verbose_name='提交时间'),
        ),
    ]
