# Generated by Django 2.1.7 on 2019-03-08 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oj', '0006_auto_20190308_2101'),
        ('submission', '0002_auto_20190308_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='lang',
            field=models.ForeignKey(default='', help_text='语言', on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='oj.Language', verbose_name='语言'),
            preserve_default=False,
        ),
    ]
