# Generated by Django 2.1.7 on 2019-03-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('submission', '0003_submission_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='judge_datetime',
            field=models.DateTimeField(blank=True, help_text='判题时间', null=True, verbose_name='判题时间'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submit_datetime',
            field=models.DateTimeField(auto_now_add=True, help_text='提交时间', verbose_name='提交时间'),
        ),
    ]
