# Generated by Django 2.1.7 on 2019-03-08 13:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oj', '0004_auto_20190308_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.CharField(default=uuid.uuid1, max_length=36, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='语言名称')),
                ('code', models.CharField(max_length=36, verbose_name='语言代码')),
                ('oj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj.OJ')),
            ],
        ),
    ]
