# Generated by Django 2.1.7 on 2019-03-08 21:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oj', '0005_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(help_text='语言代码', max_length=36, verbose_name='语言代码'),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.CharField(default=uuid.uuid1, help_text='ID', max_length=36, primary_key=True, serialize=False,
                                   verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='语言名称', max_length=128, verbose_name='语言名称'),
        ),
        migrations.AlterField(
            model_name='language',
            name='oj',
            field=models.ForeignKey(help_text='OJ', on_delete=django.db.models.deletion.CASCADE, to='oj.OJ',
                                    verbose_name='OJ'),
        ),
        migrations.AlterField(
            model_name='oj',
            name='end_sid',
            field=models.IntegerField(default=1000, help_text='结束编号', verbose_name='结束编号'),
        ),
        migrations.AlterField(
            model_name='oj',
            name='id',
            field=models.CharField(default=uuid.uuid1, help_text='ID', max_length=36, primary_key=True, serialize=False,
                                   verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oj',
            name='name',
            field=models.CharField(help_text='OJ名称', max_length=128, verbose_name='OJ名称'),
        ),
        migrations.AlterField(
            model_name='oj',
            name='start_sid',
            field=models.IntegerField(default=1000, help_text='开始编号', verbose_name='开始编号'),
        ),
        migrations.AlterField(
            model_name='oj',
            name='update_time',
            field=models.DateTimeField(auto_created=True, auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
    ]
