# Generated by Django 2.1.7 on 2019-03-10 14:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oj', '0006_auto_20190308_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id',
                 models.CharField(default=uuid.uuid1, help_text='ID', max_length=36, primary_key=True, serialize=False,
                                  verbose_name='ID')),
                ('username', models.CharField(help_text='用户名', max_length=128, verbose_name='用户名')),
                ('password', models.CharField(help_text='密码', max_length=128, verbose_name='密码')),
                ('oj', models.ForeignKey(help_text='OJ', on_delete=django.db.models.deletion.CASCADE, to='oj.OJ',
                                         verbose_name='OJ')),
            ],
        ),
    ]
