# Generated by Django 2.1.7 on 2019-03-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oj', '0007_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='nickname',
            field=models.CharField(default='', help_text='昵称', max_length=128, verbose_name='昵称'),
            preserve_default=False,
        ),
    ]
