# Generated by Django 2.1.7 on 2019-03-07 10:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.CharField(default=uuid.uuid1, max_length=36, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('soj', models.CharField(max_length=128, verbose_name='oj名称')),
                ('sid', models.IntegerField(verbose_name='编号')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('time_limit', models.CharField(max_length=128, verbose_name='时间限制')),
                ('memory_limit', models.CharField(max_length=128, verbose_name='内存限制')),
                ('description', models.TextField(verbose_name='描述')),
                ('input', models.TextField(verbose_name='输入')),
                ('output', models.TextField(verbose_name='输出')),
                ('sample_input', models.TextField(verbose_name='输入样例')),
                ('sample_output', models.TextField(verbose_name='输出样例')),
                ('source', models.TextField(blank=True, verbose_name='来源')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
