# Generated by Django 2.1.7 on 2019-03-08 21:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(help_text='描述', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.CharField(default=uuid.uuid1, help_text='ID', max_length=36, primary_key=True, serialize=False,
                                   verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input',
            field=models.TextField(help_text='输出', verbose_name='输入'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.CharField(help_text='内存限制', max_length=128, verbose_name='内存限制'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output',
            field=models.TextField(help_text='输入', verbose_name='输出'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_input',
            field=models.TextField(help_text='输入样例', verbose_name='输入样例'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_output',
            field=models.TextField(help_text='输出样例', verbose_name='输出样例'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sid',
            field=models.IntegerField(help_text='编号', verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='soj',
            field=models.CharField(help_text='OJ名称', max_length=128, verbose_name='OJ名称'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='source',
            field=models.TextField(blank=True, help_text='来源', verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.CharField(help_text='时间限制', max_length=128, verbose_name='时间限制'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(help_text='标题', max_length=128, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
    ]
